### ISSUE TITLE
How can I include caffe in my Windows based c++ project?

### ISSUE THREAD

**Issue by erogol** [terrychenism/caffe-windows-cudnn#1]
I plan to code a Windows C++ project based on Trained caffe model predictions. How should I include caffe to use my trained model for prediction ?

**Comment by RomainDWipsea** [comment]
Hi, I have the same project, did you manage to do it that way? I had some troubles to install caffe on my linux partition so I hope I can avoid installing it on the windows one. My plan is to train the networks on linux and then find a way to use the trained networks in my existing windows based C++ project. Is that possible? Thank you for your time.

**Comment by terrychenism** [comment]
a simple way for you: try to build static and dynamic library for caffe, and include caffe.hpp and its dependency in your projects. If success, let me know.Thanks.
