### ISSUE TITLE
caffe pretrained models compatibility

### ISSUE THREAD

**Issue by alitou** [terrychenism/caffe-windows-cudnn#10]
I build caffe successfully.When I want to use pretrained models in Model Zoo with all of them I get nearly the same error : error caffe.NetParameter has no field name layers,k,etc (differs on diffrent models).Is there a compatibilty issue between New codes(Models) and the source code here?

**Comment by terrychenism** [comment]
I think GoogleNet Model will lead to some problems. I have tested bvlc_reference_caffenet, vgg model, both are okay for this caffe.

**Comment by alitou** [comment]
I used all the models and got the same error.
Could you provide a code(or tutorial) to run the pretrained models in windows.

**Comment by terrychenism** [comment]
You can follow the mnist example. If it is okay, then you can try imagenet model.
