### ISSUE TITLE
lmdb exception: "mdb_env_open failed"

### ISSUE THREAD

**Issue by Sam7** [terrychenism/caffe-windows-cudnn#11]
Whenever I use lmdb as the data backend I'm seeing this exception:

```
state {
  phase: TRAIN
}
I0528 13:49:10.889911 19880 net.cpp:67] Creating Layer mnist
I0528 13:49:10.890913 19880 net.cpp:356] mnist -> data
I0528 13:49:10.890913 19880 net.cpp:356] mnist -> label
I0528 13:49:10.890913 19880 net.cpp:96] Setting up mnist
F0528 13:49:10.890913 19880 data_layer.cpp:62] Check failed: mdb_env_open(mdb_en
v_, this->layer_param_.data_param().source().c_str(), 0x20000|0x200000, 0664) ==
 0 (3 vs. 0) mdb_env_open failed
*** Check failure stack trace: ***
```

I can train mnist from the leveldb, no problem. but when I switch to

```
source: "mnist_test_lmdb"
backend: LMDB
```

I just get an error. I tried full paths, relative paths, no luck...
Here is the examples/minst folder as a lmdb sample: https://drive.google.com/file/d/0BzA79A-ykBc2c2pXYTNjcmFOVDA/view?usp=sharing

Any suggestions?

I can open the lmdb database with a .net application of mine, so I don't think it's corrupt.
Cheers!

**Comment by terrychenism** [comment]
All the caffe windows version has lmdb problems now.
