### ISSUE TITLE
GeneratePB.bat

### ISSUE THREAD

**Issue by shaneahmed** [terrychenism/caffe-windows-cudnn#14]
Error   1   error MSB3073: The command "set origin_dir=Í%
cd ../../
"./scripts/GeneratePB.bat"
cd %origin_dir%
:VCEnd" exited with code 1. C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets  122 5   MainCaller

Can't understand this error

**Comment by terrychenism** [comment]
to remove all command in post-build event and copy dll file to bin folder
