### ISSUE TITLE
train for fcn by caffe-windows-cudnn

### ISSUE THREAD

**Issue by northchert** [terrychenism/caffe-windows-cudnn#15]
The  caffe-windows-cudnn can test the fcn8 well. But the big problem is how to train for the fcn8 model. The layer of input is datalayer, then it could not build lmdb file in the windows for many times. So, is there a codes for inputting images directly and successful training?

**Comment by terrychenism** [comment]
You can follow the comments from https://github.com/BVLC/caffe/issues/1698 and convert the data and label lmdb.

**Comment by xjtuljy** [comment]
@northchert , how did you test the fcn8? in the downloaded zip file, there is only one folder (example/fcn) related to fcn. Or did you follow the instruction from the model zoo?
