### ISSUE TITLE
Is this version of caffe has any function too read opencv mat into caffe format?

### ISSUE THREAD

**Issue by erogol** [terrychenism/caffe-windows-cudnn#2]
I try to implement a real-time system based on opencv backend. Is there any function to read opencv mat into caffe format to give it a trained model prediction. I guess original Caffe merged such 
PR recently. https://github.com/BVLC/caffe/pull/1416 . If it is not enbaled in this version, can I extend to include this pull?

**Comment by terrychenism** [comment]
Here is sample code that convert opencv format to datum.


          cv::Mat cv_img;
	 bool is_color = 1;

	 const int height = 224, width = 224; // 224 for vgg model; 227 for reference model
	 int cv_read_flag = (is_color ? CV_LOAD_IMAGE_COLOR :
		CV_LOAD_IMAGE_GRAYSCALE);

	 cv::Mat cv_img_origin; // = cv::imread(filename, cv_read_flag);

	// VideoWriter videoWriter;
	// videoWriter.open("out.avi",CV_FOURCC('M','J','P','G'), 25, Size(RESOLUTION_X ,RESOLUTION_Y),true);
    // if (!videoWriter.isOpened()) cout << "cannot create video" << endl;


	while(capture.read(cv_img_origin) /*&& i < 100 */)
	{
		
	  resize(cv_img_origin, cv_img_origin, wsize, 0, 0, INTER_CUBIC); 

	  if (!cv_img_origin.data) {
		LOG(ERROR) << "Could not open or find file " << filename;
		return false;
	  }
	  if (height > 0 && width > 0) {
		cv::resize(cv_img_origin, cv_img, cv::Size(width, height));
	  } else {
		cv_img = cv_img_origin;
	  }

	  int num_channels = (is_color ? 3 : 1);
	  datum.set_channels(num_channels);
	  datum.set_height(cv_img.rows);
	  datum.set_width(cv_img.cols);
	  datum.set_label(0);
	  datum.clear_data();
	  datum.clear_float_data();
	  string* datum_string = datum.mutable_data();
	  if (is_color) {
		for (int c = 0; c < num_channels; ++c) {
		  for (int h = 0; h < cv_img.rows; ++h) {
			for (int w = 0; w < cv_img.cols; ++w) {
			  datum_string->push_back(
				static_cast<char>(cv_img.at<cv::Vec3b>(h, w)[c]));
			}
		  }
		}
	  } else {  // Faster than repeatedly testing is_color for each pixel w/i loop
		for (int h = 0; h < cv_img.rows; ++h) {
		  for (int w = 0; w < cv_img.cols; ++w) {
			datum_string->push_back(
			  static_cast<char>(cv_img.at<uchar>(h, w)));
			}
		  }
	  }



	  //get the blob
	  Blob<float>* blob = new Blob<float>(1, datum.channels(), datum.height(), datum.width());
  
	  //get the blobproto
	  BlobProto blob_proto;
	  blob_proto.set_num(1);
	  blob_proto.set_channels(datum.channels());
	  blob_proto.set_height(datum.height());
	  blob_proto.set_width(datum.width());
	  const int data_size = datum.channels() * datum.height() * datum.width();
	  int size_in_datum = std::max<int>(datum.data().size(),
										datum.float_data_size());
	  for (int i = 0; i < size_in_datum; ++i) {
		blob_proto.add_data(0.);
	  }
	  const string& data = datum.data();
	  if (data.size() != 0) {
		for (int i = 0; i < size_in_datum; ++i) {
		  blob_proto.set_data(i, blob_proto.data(i) + (uint8_t)data[i]);
		}
	  }
  
	  //set data into blob
	  blob->FromProto(blob_proto);
 
	  //fill the vector
	  vector<Blob<float>*> bottom;
	  bottom.push_back(blob);

	  float type = 0.0;
 
	  const vector<Blob<float>*>& result =  caffe_test_net.Forward(bottom, &type);

**Comment by erogol** [comment]
Thanks for the code. I am confused about "datum". What is this, would you tell me?

**Comment by erogol** [comment]
I see the answer to my question :)
