### ISSUE TITLE
Compilation error in Win8 VS2012

### ISSUE THREAD

**Issue by erogol** [terrychenism/caffe-windows-cudnn#3]
As I build the code in Debug mode x64 platform, it raises

LINK : fatal error LNK1104: cannot open file 'libboost_date_time-vc110-mt-gd-1_55.lib'

Also there is not such a file in 3rdparty/lib

**Comment by terrychenism** [comment]
download from here https://www.dropbox.com/s/121o1so5hj8zz64/3rdparty.rar?dl=0

**Comment by erogol** [comment]
This RAR does not include the file

**Comment by erogol** [comment]
If I compile it in Release mode, it is ok. But in debug mode it gives the same compilation error.

**Comment by terrychenism** [comment]
yes, only release is okay.
