### ISSUE TITLE
Runtime problem of MainCaller.cpp

### ISSUE THREAD

**Issue by erogol** [terrychenism/caffe-windows-cudnn#4]
After the compilation in Release mode with any tools like train_net.cpp, test_net.cpp, if I run MainCaller.exe, it raises "The procedure entry point cudnnSetPoolingDescriptor could not be located in the dynamic link library "

I installed cudnn from nvidia website and add its location to "path" and I set the include and linker libraries of the VS solution accordingly but the error persists. Any idea for the solution ?

Sorry for the long run headache :(

**Comment by terrychenism** [comment]
I think you can try to run mnist demo.

**Comment by erogol** [comment]
The problem is; if I use your cudnn dll in bin folder, it is okay but if I download the latest one from Nvidia site, it raises that error. 

However, I realized that my architecture is not enough to run cudnn since it is < 3.x compute capability. Can I compile the library without cudnn? You can suggest the other caffe-windows version bit is pretty old compared to yours,

**Comment by terrychenism** [comment]
Yes, you can use https://github.com/niuzhiheng/caffe without cudnn
