### ISSUE TITLE
Can't download the 3rdparty.rar

### ISSUE THREAD

**Issue by yesafdsaf** [terrychenism/caffe-windows-cudnn#5]
Hello @terrychenism,Thanks for your develpment of caffe-windows-cudnn. But I can not download the 3rdparty.rar through the link provided in the README because of the firewall. So can you please give me another link ?  Thanks in advance.

**Comment by terrychenism** [comment]
If you are in China, I think you cannot get access to dropbox link. Here is a new link: http://share.weiyun.com/c29bf74b3a3e026fea87445c0bd126dd?pt=1
