### ISSUE TITLE
Install pyCaffe

### ISSUE THREAD

**Issue by erfannoury** [terrychenism/caffe-windows-cudnn#7]
Hello and thank you for great effort
I wanted to ask whether pycaffe can be installed on Windows? Have you been able to do so? I couldn't find any documentation on installing the python wrapper after caffe is built and installed. It would be great if you could provide some guidance.

**Comment by terrychenism** [comment]
Actually I have try to compile pycaffe on Windows, but some errors always existed. I will check it soon.

Thanks!

**Comment by erfannoury** [comment]
Thank you. I am looking forward to it.
